export const clerkLightAppearance = {
  variables: {
    borderRadius: "6px",
    colorBackground: "#ffffff",
    colorDanger: "#dc2626",
    colorInputBackground: "#ffffff",
    colorInputText: "#18181b",
    colorPrimary: "#1d4ed8",
    colorSuccess: "#059669",
    colorText: "#18181b",
    colorTextSecondary: "#52525b",
    fontFamily: '"Inter", system-ui, -apple-system, sans-serif',
  },
  elements: {
    card: {
      backgroundColor: "#ffffff",
      border: "1px solid rgba(0,0,0,0.06)",
      borderRadius: "10px",
      boxShadow: "0 20px 25px -5px rgba(0,0,0,0.1)",
    },
    footerActionLink: {
      color: "#1d4ed8",
      fontWeight: 500,
    },
    formButtonPrimary: {
      backgroundColor: "#1d4ed8",
      fontSize: "13px",
      fontWeight: 500,
      height: "40px",
      textTransform: "none",
      "&:hover": { backgroundColor: "#2563eb" },
    },
    formFieldInput: {
      backgroundColor: "#ffffff",
      border: "1px solid rgba(0,0,0,0.10)",
      borderRadius: "6px",
      fontSize: "13px",
      height: "40px",
    },
    formFieldLabel: {
      color: "#52525b",
      fontSize: "12px",
      fontWeight: 500,
      textTransform: "none",
    },
    headerSubtitle: { color: "#52525b", fontSize: "13px" },
    headerTitle: { fontSize: "16px", fontWeight: 500 },
    organizationSwitcherTrigger: {
      borderRadius: "6px",
      fontSize: "13px",
      padding: "6px 10px",
    },
    rootBox: { width: "100%" },
    socialButtonsBlockButton: {
      backgroundColor: "#ffffff",
      border: "1px solid rgba(0,0,0,0.10)",
      borderRadius: "6px",
      color: "#18181b",
      fontSize: "13px",
      fontWeight: 500,
      height: "40px",
    },
  },
};

export const clerkDarkAppearance = {
  variables: {
    borderRadius: "6px",
    colorBackground: "#131316",
    colorDanger: "#ef4444",
    colorInputBackground: "#131316",
    colorInputText: "#fafafa",
    colorPrimary: "#3b82f6",
    colorSuccess: "#10b981",
    colorText: "#fafafa",
    colorTextSecondary: "#a1a1aa",
    fontFamily: '"Inter", system-ui, -apple-system, sans-serif',
  },
  elements: {
    card: {
      backgroundColor: "#131316",
      border: "1px solid rgba(255,255,255,0.10)",
      borderRadius: "10px",
      boxShadow: "0 20px 25px -5px rgba(0,0,0,0.5)",
    },
    footerActionLink: {
      color: "#3b82f6",
      fontWeight: 500,
    },
    formButtonPrimary: {
      backgroundColor: "#3b82f6",
      fontSize: "13px",
      fontWeight: 500,
      height: "40px",
      textTransform: "none",
      "&:hover": { backgroundColor: "#60a5fa" },
    },
    formFieldInput: {
      backgroundColor: "#131316",
      border: "1px solid rgba(255,255,255,0.10)",
      borderRadius: "6px",
      fontSize: "13px",
      height: "40px",
    },
    formFieldLabel: {
      color: "#a1a1aa",
      fontSize: "12px",
      fontWeight: 500,
      textTransform: "none",
    },
    headerSubtitle: { color: "#a1a1aa", fontSize: "13px" },
    headerTitle: { fontSize: "16px", fontWeight: 500 },
    organizationSwitcherTrigger: {
      borderRadius: "6px",
      fontSize: "13px",
      padding: "6px 10px",
    },
    rootBox: { width: "100%" },
    socialButtonsBlockButton: {
      backgroundColor: "#131316",
      border: "1px solid rgba(255,255,255,0.10)",
      borderRadius: "6px",
      color: "#fafafa",
      fontSize: "13px",
      fontWeight: 500,
      height: "40px",
    },
  },
};
