export const CSRD_DATA_POINTS = [
  { id: "double_materiality", label: "Dvojí materialita", standard: "ESRS 1" },
  { id: "governance_oversight", label: "ESG dohled vedení", standard: "ESRS 2 GOV" },
  { id: "esg_policy", label: "ESG politika a cíle", standard: "ESRS 2 MDR" },
  { id: "scope1_emissions", label: "Scope 1 emise", standard: "ESRS E1" },
  { id: "scope2_emissions", label: "Scope 2 emise", standard: "ESRS E1" },
  { id: "scope3_emissions", label: "Scope 3 emise", standard: "ESRS E1" },
  { id: "energy_consumption", label: "Spotřeba energie", standard: "ESRS E1" },
  { id: "water_usage", label: "Spotřeba vody", standard: "ESRS E3" },
  { id: "waste_management", label: "Odpadové toky", standard: "ESRS E5" },
  { id: "pollution_incidents", label: "Environmentální incidenty", standard: "ESRS E2" },
  { id: "biodiversity_impact", label: "Biodiverzita", standard: "ESRS E4" },
  { id: "climate_risk_assessment", label: "Klimatická rizika", standard: "ESRS E1" },
  { id: "workforce_headcount", label: "Pracovní síla", standard: "ESRS S1" },
  { id: "health_safety", label: "BOZP ukazatele", standard: "ESRS S1" },
  { id: "training_hours", label: "Školení a rozvoj", standard: "ESRS S1" },
  { id: "diversity_metrics", label: "Diverzitní metriky", standard: "ESRS S1" },
  { id: "worker_grievance", label: "Kanál pro stížnosti pracovníků", standard: "ESRS S1" },
  { id: "supply_chain_due_diligence", label: "Due diligence dodavatelů", standard: "ESRS G1" },
  { id: "supplier_esg_questionnaire", label: "Dodavatelský ESG dotazník", standard: "ESRS G1" },
  { id: "customer_privacy", label: "Ochrana zákaznických dat", standard: "ESRS S4" },
  { id: "business_conduct_policy", label: "Politika obchodního jednání", standard: "ESRS G1" },
  { id: "anti_corruption_training", label: "Protikorupční školení", standard: "ESRS G1" },
  { id: "tax_transparency", label: "Daňová transparentnost", standard: "ESRS G1" },
  { id: "report_approval", label: "Schvalování ESG reportu", standard: "CSRD" },
] as const;

export const CSRD_SUPPLY_CHAIN_QUESTIONNAIRE = [
  "Máte určeného vlastníka ESG reportingu a kontaktní osobu pro dodavatelské dotazníky?",
  "Měříte Scope 1 a Scope 2 emise a dokážete doložit metodiku výpočtu?",
  "Máte odhad relevantních Scope 3 emisí v hodnotovém řetězci?",
  "Evidujete spotřebu energie, vody a významné odpadové toky?",
  "Probíhá hodnocení environmentálních incidentů a nápravných opatření?",
  "Vedete data o pracovní síle, BOZP, školení a diverzitních metrikách?",
  "Máte politiku obchodního jednání, etický kodex nebo obdobný dokument?",
  "Školíte relevantní pracovníky v protikorupčních a compliance pravidlech?",
  "Provádíte ESG due diligence u vlastních klíčových dodavatelů?",
  "Umíte dodat auditovatelnou stopu zdrojů dat pro ESG odpovědi?",
] as const;
