export type Iso27001AnnexMapping = {
  articleRef: string;
  controlKey: string;
  title: string;
};

export const ISO27001_CERTIFICATION_BODIES = [
  {
    name: "Bureau Veritas Czech Republic",
    url: "https://www.bureauveritas.cz/nase-sluzby/certifikace/iso-27001",
  },
  {
    name: "LRQA",
    url: "https://www.lrqa.com/en-gb/iso-27001/",
  },
] as const;

export const ISO27001_ANNEX_A_MAPPINGS: Iso27001AnnexMapping[] = [
  { articleRef: "A.5.1", title: "Policies for information security", controlKey: "ctrl_security_policy_approved" },
  { articleRef: "A.5.2", title: "Information security roles and responsibilities", controlKey: "ctrl_security_roles_responsibilities" },
  { articleRef: "A.5.3", title: "Segregation of duties", controlKey: "ctrl_privileged_access_reviewed" },
  { articleRef: "A.5.4", title: "Management responsibilities", controlKey: "ctrl_management_review" },
  { articleRef: "A.5.5", title: "Contact with authorities", controlKey: "ctrl_incident_plan_documented" },
  { articleRef: "A.5.6", title: "Contact with special interest groups", controlKey: "ctrl_threat_intelligence" },
  { articleRef: "A.5.7", title: "Threat intelligence", controlKey: "ctrl_threat_intelligence" },
  { articleRef: "A.5.8", title: "Information security in project management", controlKey: "ctrl_secure_development_policy" },
  { articleRef: "A.5.9", title: "Inventory of information and other associated assets", controlKey: "ctrl_asset_inventory" },
  { articleRef: "A.5.10", title: "Acceptable use of information and other associated assets", controlKey: "ctrl_security_policy_approved" },
  { articleRef: "A.5.11", title: "Return of assets", controlKey: "ctrl_offboarding_access_revoked" },
  { articleRef: "A.5.12", title: "Classification of information", controlKey: "ctrl_data_classification" },
  { articleRef: "A.5.13", title: "Labelling of information", controlKey: "ctrl_data_classification" },
  { articleRef: "A.5.14", title: "Information transfer", controlKey: "ctrl_information_transfer_rules" },
  { articleRef: "A.5.15", title: "Access control", controlKey: "ctrl_identity_lifecycle_policy" },
  { articleRef: "A.5.16", title: "Identity management", controlKey: "ctrl_identity_lifecycle_policy" },
  { articleRef: "A.5.17", title: "Authentication information", controlKey: "ctrl_password_policy" },
  { articleRef: "A.5.18", title: "Access rights", controlKey: "ctrl_privileged_access_reviewed" },
  { articleRef: "A.5.19", title: "Information security in supplier relationships", controlKey: "ctrl_vendor_security_assessment" },
  { articleRef: "A.5.20", title: "Addressing information security within supplier agreements", controlKey: "ctrl_supplier_contract_security" },
  { articleRef: "A.5.21", title: "Managing information security in the ICT supply chain", controlKey: "ctrl_supplier_monitoring" },
  { articleRef: "A.5.22", title: "Monitoring, review and change management of supplier services", controlKey: "ctrl_supplier_monitoring" },
  { articleRef: "A.5.23", title: "Information security for use of cloud services", controlKey: "ctrl_secure_configuration_baseline" },
  { articleRef: "A.5.24", title: "Information security incident management planning and preparation", controlKey: "ctrl_incident_plan_documented" },
  { articleRef: "A.5.25", title: "Assessment and decision on information security events", controlKey: "ctrl_logging_monitoring" },
  { articleRef: "A.5.26", title: "Response to information security incidents", controlKey: "ctrl_incident_72h_notification" },
  { articleRef: "A.5.27", title: "Learning from information security incidents", controlKey: "ctrl_incident_plan_documented" },
  { articleRef: "A.5.28", title: "Collection of evidence", controlKey: "ctrl_document_control" },
  { articleRef: "A.5.29", title: "Information security during disruption", controlKey: "ctrl_business_continuity_plan" },
  { articleRef: "A.5.30", title: "ICT readiness for business continuity", controlKey: "ctrl_disaster_recovery_test" },
  { articleRef: "A.5.31", title: "Legal, statutory, regulatory and contractual requirements", controlKey: "ctrl_document_control" },
  { articleRef: "A.5.32", title: "Intellectual property rights", controlKey: "ctrl_document_control" },
  { articleRef: "A.5.33", title: "Protection of records", controlKey: "ctrl_document_control" },
  { articleRef: "A.5.34", title: "Privacy and protection of PII", controlKey: "ctrl_privacy_notice_current" },
  { articleRef: "A.5.35", title: "Independent review of information security", controlKey: "ctrl_internal_audit_program" },
  { articleRef: "A.5.36", title: "Compliance with policies, rules and standards", controlKey: "ctrl_control_exceptions_tracked" },
  { articleRef: "A.5.37", title: "Documented operating procedures", controlKey: "ctrl_document_control" },
  { articleRef: "A.6.1", title: "Screening", controlKey: "ctrl_identity_lifecycle_policy" },
  { articleRef: "A.6.2", title: "Terms and conditions of employment", controlKey: "ctrl_security_roles_responsibilities" },
  { articleRef: "A.6.3", title: "Information security awareness, education and training", controlKey: "ctrl_security_training_annual" },
  { articleRef: "A.6.4", title: "Disciplinary process", controlKey: "ctrl_security_policy_approved" },
  { articleRef: "A.6.5", title: "Responsibilities after termination or change of employment", controlKey: "ctrl_offboarding_access_revoked" },
  { articleRef: "A.6.6", title: "Confidentiality or non-disclosure agreements", controlKey: "ctrl_supplier_contract_security" },
  { articleRef: "A.6.7", title: "Remote working", controlKey: "ctrl_remote_work_policy" },
  { articleRef: "A.6.8", title: "Information security event reporting", controlKey: "ctrl_incident_72h_notification" },
  { articleRef: "A.7.1", title: "Physical security perimeters", controlKey: "ctrl_physical_access_control" },
  { articleRef: "A.7.2", title: "Physical entry", controlKey: "ctrl_physical_access_control" },
  { articleRef: "A.7.3", title: "Securing offices, rooms and facilities", controlKey: "ctrl_physical_access_control" },
  { articleRef: "A.7.4", title: "Physical security monitoring", controlKey: "ctrl_physical_access_control" },
  { articleRef: "A.7.5", title: "Protecting against physical and environmental threats", controlKey: "ctrl_physical_access_control" },
  { articleRef: "A.7.6", title: "Working in secure areas", controlKey: "ctrl_physical_access_control" },
  { articleRef: "A.7.7", title: "Clear desk and clear screen", controlKey: "ctrl_security_policy_approved" },
  { articleRef: "A.7.8", title: "Equipment siting and protection", controlKey: "ctrl_asset_inventory" },
  { articleRef: "A.7.9", title: "Security of assets off-premises", controlKey: "ctrl_mobile_device_management" },
  { articleRef: "A.7.10", title: "Storage media", controlKey: "ctrl_media_disposal" },
  { articleRef: "A.7.11", title: "Supporting utilities", controlKey: "ctrl_business_continuity_plan" },
  { articleRef: "A.7.12", title: "Cabling security", controlKey: "ctrl_physical_access_control" },
  { articleRef: "A.7.13", title: "Equipment maintenance", controlKey: "ctrl_asset_inventory" },
  { articleRef: "A.7.14", title: "Secure disposal or re-use of equipment", controlKey: "ctrl_media_disposal" },
  { articleRef: "A.8.1", title: "User endpoint devices", controlKey: "ctrl_device_encryption" },
  { articleRef: "A.8.2", title: "Privileged access rights", controlKey: "ctrl_privileged_access_reviewed" },
  { articleRef: "A.8.3", title: "Information access restriction", controlKey: "ctrl_guest_access_controlled" },
  { articleRef: "A.8.4", title: "Access to source code", controlKey: "ctrl_code_review_required" },
  { articleRef: "A.8.5", title: "Secure authentication", controlKey: "ctrl_mfa_all_users" },
  { articleRef: "A.8.6", title: "Capacity management", controlKey: "ctrl_logging_monitoring" },
  { articleRef: "A.8.7", title: "Protection against malware", controlKey: "ctrl_endpoint_protection" },
  { articleRef: "A.8.8", title: "Management of technical vulnerabilities", controlKey: "ctrl_vulnerability_management" },
  { articleRef: "A.8.9", title: "Configuration management", controlKey: "ctrl_secure_configuration_baseline" },
  { articleRef: "A.8.10", title: "Information deletion", controlKey: "ctrl_data_retention_schedule" },
  { articleRef: "A.8.11", title: "Data masking", controlKey: "ctrl_data_classification" },
  { articleRef: "A.8.12", title: "Data leakage prevention", controlKey: "ctrl_secrets_management" },
  { articleRef: "A.8.13", title: "Information backup", controlKey: "ctrl_backup_policy" },
  { articleRef: "A.8.14", title: "Redundancy of information processing facilities", controlKey: "ctrl_disaster_recovery_test" },
  { articleRef: "A.8.15", title: "Logging", controlKey: "ctrl_logging_monitoring" },
  { articleRef: "A.8.16", title: "Monitoring activities", controlKey: "ctrl_security_event_alerting" },
  { articleRef: "A.8.17", title: "Clock synchronization", controlKey: "ctrl_clock_sync" },
  { articleRef: "A.8.18", title: "Use of privileged utility programs", controlKey: "ctrl_privileged_access_reviewed" },
  { articleRef: "A.8.19", title: "Installation of software on operational systems", controlKey: "ctrl_change_management" },
  { articleRef: "A.8.20", title: "Networks security", controlKey: "ctrl_network_segmentation" },
  { articleRef: "A.8.21", title: "Security of network services", controlKey: "ctrl_network_segmentation" },
  { articleRef: "A.8.22", title: "Segregation of networks", controlKey: "ctrl_network_segmentation" },
  { articleRef: "A.8.23", title: "Web filtering", controlKey: "ctrl_endpoint_protection" },
  { articleRef: "A.8.24", title: "Use of cryptography", controlKey: "ctrl_cryptography_policy" },
  { articleRef: "A.8.25", title: "Secure development life cycle", controlKey: "ctrl_secure_development_policy" },
  { articleRef: "A.8.26", title: "Application security requirements", controlKey: "ctrl_secure_development_policy" },
  { articleRef: "A.8.27", title: "Secure system architecture and engineering principles", controlKey: "ctrl_secure_development_policy" },
  { articleRef: "A.8.28", title: "Secure coding", controlKey: "ctrl_code_review_required" },
  { articleRef: "A.8.29", title: "Security testing in development and acceptance", controlKey: "ctrl_code_review_required" },
  { articleRef: "A.8.30", title: "Outsourced development", controlKey: "ctrl_supplier_contract_security" },
  { articleRef: "A.8.31", title: "Separation of development, test and production environments", controlKey: "ctrl_change_management" },
  { articleRef: "A.8.32", title: "Change management", controlKey: "ctrl_change_management" },
  { articleRef: "A.8.33", title: "Test information", controlKey: "ctrl_data_classification" },
  { articleRef: "A.8.34", title: "Protection of information systems during audit testing", controlKey: "ctrl_internal_audit_program" },
];
